version: '3'
services:
  deluxe:
    image: bettercallshao/deluxe
    build:
      context: .
      dockerfile: df/Dockerfile.deluxe
    ports:
    - "8080:8080"
    environment:
      spring_profiles_active: container
      spring_datasource_url: jdbc:postgresql://postgres:5432/wiser
      spring_datasource_username: postgres
      spring_datasource_password: postgres
    links:
    - postgres
  manhattan:
    image: bettercallshao/manhattan
    build:
      context: .
      dockerfile: df/Dockerfile.manhattan
    environment:
      spring_profiles_active: container
      manhattan_url: https://www.technologyreview.com/topnews.rss
      spring_datasource_url: jdbc:postgresql://postgres:5432/wiser
      spring_datasource_username: postgres
      spring_datasource_password: postgres
    links:
    - postgres
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /postgres-data
      POSTGRES_DB: wiser
    volumes:
    - "postgres-data:/postgres-data"
volumes:
  postgres-data:
