apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /postgres-data
        env:
        - name: PGDATA
          value: /postgres-data/data
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: wiser-config
              key: spring_datasource_password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: wiser-config
              key: spring_datasource_username
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: wiser-config
              key: database
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
